import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from core.vector_store import (
    get_vector_store,
    load_vector_store,
    retrieve_vector_store
)

load_dotenv()


def get_llm():
    return ChatGroq(
        model="openai/gpt-oss-20b",
        api_key=os.getenv("GROQ_API_KEY"),
        temperature=0,
        max_tokens=2048
    )


def format_docs(docs):
    return "\n\n".join(
        doc.page_content
        for doc in docs
    )


def create_rag_chain(vector_store):

    retriever = retrieve_vector_store(vector_store)

    model = get_llm()

    prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """You are an expert assistant answering questions based on the provided video transcription context.

Guidelines:
- The context was generated by speech-to-text, so names, brand terms, and acronyms may have phonetic transcription variations (e.g., "Jeff" vs "Jev", "JGBT" vs "ChatGPT", "Versal" vs "Vercel", "Cloud Code" vs "Claude Code"). Connect related concepts accurately.
- Answer the user's question clearly, informatively, and concisely based on the context.
- Only respond with "I don't know" if the topic is completely absent from the context.

Context:
{context}
"""
        ),
        (
            "human",
            "{question}"
        )
    ])

    chain = (
        {
            "context": retriever | RunnableLambda(format_docs),
            "question": RunnablePassthrough()
        }
        | prompt
        | model
        | StrOutputParser()
    )

    return chain


def build_rag_chain(transcripts: str):
    vector_store = get_vector_store(transcripts)
    return create_rag_chain(vector_store)


def load_rag_chain():
    vector_store = load_vector_store()
    return create_rag_chain(vector_store)


def ask_question(chain, question: str):
    answer = chain.invoke(question)
    return answer