import os
import shutil
import uuid
import yt_dlp
from pydub import AudioSegment

DOWNLOAD_DIR = "downloads"
os.makedirs(DOWNLOAD_DIR, exist_ok=True)


class AudioChunksList(list):
    """Subclass of list holding audio chunk paths with cleanup capability.
    Operates identically to a standard list for complete backwards compatibility.
    """
    def __init__(self, chunks: list[str], temp_files: list[str] = None, session_dir: str = None):
        super().__init__(chunks)
        self.temp_files = temp_files or []
        self.session_dir = session_dir

    def cleanup(self):
        """Remove all intermediate and chunk audio files created during processing."""
        cleanup_files(self.temp_files)
        cleanup_files(list(self))
        if self.session_dir and os.path.exists(self.session_dir):
            cleanup_session_dir(self.session_dir)


def cleanup_files(file_paths: list[str]):
    """Safely remove a list of audio or chunk files."""
    for p in file_paths:
        try:
            if p and os.path.isfile(p):
                os.remove(p)
        except Exception as e:
            print(f"Warning: Could not remove file {p}: {e}")


def cleanup_session_dir(directory: str):
    """Safely remove a temporary session directory and all its contents."""
    try:
        if directory and os.path.isdir(directory):
            shutil.rmtree(directory, ignore_errors=True)
    except Exception as e:
        print(f"Warning: Could not remove directory {directory}: {e}")


def purge_all_downloads(target_dir: str = DOWNLOAD_DIR):
    """Purge all generated audio files (.wav, .webm, .m4a, .mp3) from the downloads directory.
    Safe for production maintenance or cleanup routines.
    """
    if not os.path.exists(target_dir):
        return
    for item in os.listdir(target_dir):
        item_path = os.path.join(target_dir, item)
        try:
            if os.path.isfile(item_path) and item_path.lower().endswith(('.wav', '.webm', '.m4a', '.mp3', '.ogg')):
                os.remove(item_path)
            elif os.path.isdir(item_path) and item.startswith("session_"):
                shutil.rmtree(item_path, ignore_errors=True)
        except Exception as e:
            print(f"Warning: Could not purge {item_path}: {e}")


def download_youtube_audio(url: str, output_dir: str = DOWNLOAD_DIR) -> str:
    os.makedirs(output_dir, exist_ok=True)
    output_template = os.path.join(
        output_dir,
        "%(title)s.%(ext)s"
    )

    # Detect installed JS runtime (e.g. Node.js) to solve YouTube JS challenges
    js_runtimes = {}
    if shutil.which("node"):
        js_runtimes["node"] = {}
    elif shutil.which("deno"):
        js_runtimes["deno"] = {}

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": output_template,
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "wav",
                "preferredquality": "192",
            }
        ],
        "quiet": True,
        "noplaylist": True,
        "js_runtimes": js_runtimes,
        "extractor_args": {
            "youtube": {
                "player_client": ["web_creator", "mweb", "android", "ios", "web"]
            }
        },
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)

        # Get the final filename generated by yt-dlp
        filename = ydl.prepare_filename(info)

        # FFmpeg changes the extension to .wav
        filename = os.path.splitext(filename)[0] + ".wav"

    return filename


def convert_to_wav(input_file:str, output_dir:str=None)->str:
    """Convert an audio file to WAV format using pydub."""
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        base_name = os.path.splitext(os.path.basename(input_file))[0]
        output_path = os.path.join(output_dir, f"{base_name}_converted.wav")
    else:
        output_path = os.path.splitext(input_file)[0] + "_converted.wav"

    audio = AudioSegment.from_file(input_file)
    audio = audio.set_channels(1).set_frame_rate(16000)  # Convert to mono

    audio.export(output_path, format="wav")
    return output_path


def chunk_audio(wav_path:str, chunk_minutes:int=1, output_dir:str=None)->list:
    """Audio chunking function that splits a WAV file into smaller chunks of specified duration."""
    audio = AudioSegment.from_wav(wav_path)
    chunk_ms = chunk_minutes * 60 * 1000
    chunks = []
    
    base_dir = output_dir or os.path.dirname(wav_path) or "."
    base_name = os.path.splitext(os.path.basename(wav_path))[0]

    for i, start in enumerate(range(0, len(audio), chunk_ms)):
        chunk = audio[start:start+chunk_ms]
        chunk_path = os.path.join(base_dir, f"{base_name}_chunk_{i}.wav")
        chunk.export(chunk_path, format="wav")
        chunks.append(chunk_path)
    return chunks


def process_input(source: str, session_id: str = None) -> AudioChunksList:
    """Process the input source (YouTube URL or local audio file).
    Returns an AudioChunksList (acts as list of chunk paths, with .cleanup() method).
    """
    clean_source = source.strip().strip("'\"")
    
    # Session-isolated directory prevents file collisions across concurrent users
    session_dir = None
    target_dir = DOWNLOAD_DIR
    if session_id:
        session_dir = os.path.join(DOWNLOAD_DIR, f"session_{session_id}")
        target_dir = session_dir
        os.makedirs(target_dir, exist_ok=True)

    temp_files = []

    if clean_source.startswith("http://") or clean_source.startswith("https://"):
        print(f"Downloading audio from YouTube URL: {clean_source}")
        downloaded_file = download_youtube_audio(clean_source, output_dir=target_dir)
        temp_files.append(downloaded_file)
        wav_file = convert_to_wav(downloaded_file, output_dir=target_dir)
        temp_files.append(wav_file)
    elif os.path.isfile(clean_source):
        print(f"Converting local audio file to WAV: {clean_source}")
        wav_file = convert_to_wav(clean_source, output_dir=target_dir)
        temp_files.append(wav_file)
    else:
        raise ValueError(
            f"Invalid input: '{source}'. Please enter a valid YouTube URL (e.g., https://youtu.be/...) "
            f"or an existing local audio file path."
        )

    print(f"Chunking audio file: {wav_file}")
    chunks = chunk_audio(wav_file, output_dir=target_dir)
    print(f"Created {len(chunks)} audio chunks.")

    return AudioChunksList(chunks, temp_files=temp_files, session_dir=session_dir)

