import os
import yt_dlp
from pydub import AudioSegment

DOWNLOAD_DIR = "downloads"
os.makedirs(DOWNLOAD_DIR, exist_ok=True)


def download_youtube_audio(url: str) -> str:
    output_template = os.path.join(
        DOWNLOAD_DIR,
        "%(title)s.%(ext)s"
    )

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": output_template,
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "wav",
                "preferredquality": "192",
            }
        ],
        "quiet": True,
        "noplaylist": True,
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)

        # Get the final filename generated by yt-dlp
        filename = ydl.prepare_filename(info)

        # FFmpeg changes the extension to .wav
        filename = os.path.splitext(filename)[0] + ".wav"

    return filename


def convert_to_wav(input_file:str)->str:
    """Convert an audio file to WAV format using pydub."""
    output_path=os.path.splitext(input_file)[0] + "_converted.wav"
    audio=AudioSegment.from_file(input_file)
    audio=audio.set_channels(1).set_frame_rate(16000)  # Convert to mono

    audio.export(output_path, format="wav")
    return output_path


def chunk_audio(wav_path:str,chunk_minutes:int=1)->list:
    """Audio chunking function that splits a WAV file into smaller chunks of specified duration.
    """

    audio=AudioSegment.from_wav(wav_path)
    chunk_ms=chunk_minutes*60*1000
    chunks=[]
    for i,start in enumerate(range(0,len(audio),chunk_ms)):
        chunk=audio[start:start+chunk_ms]
        chunk_path=f"{wav_path}_chunk_{i}.wav"
        chunk.export(chunk_path,format="wav")
        chunks.append(chunk_path)
    return chunks


def process_input(source:str)->list:
    """Process the input source, which can be a YouTube URL or a local audio file path.
    Returns a list of paths to the processed audio chunks.
    """
    if source.startswith("http"):
        # Download and convert YouTube audio
        print(f"Downloading audio from YouTube URL: {source}")
        downloaded_file=download_youtube_audio(source)
        wav_file=convert_to_wav(downloaded_file)
    else:
        # Convert local audio file to WAV
        print(f"Converting local audio file to WAV: {source}")
        wav_file=convert_to_wav(source)

    # Chunk the WAV file into smaller segments
    print(f"Chunking audio file: {wav_file}")
    chunks=chunk_audio(wav_file)
    print(f"Created {len(chunks)} audio chunks.")
    return chunks